name: Dochi
options:
  bundleIdPrefix: com.hckim
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  onnxruntime-swift-package-manager:
    url: https://github.com/microsoft/onnxruntime-swift-package-manager.git
    from: "1.20.0"
  mcp-swift-sdk:
    url: https://github.com/modelcontextprotocol/swift-sdk.git
    from: "0.10.2"
  supabase-swift:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.0.0"
  VRMKit:
    url: https://github.com/tattn/VRMKit.git
    from: "0.5.0"

targets:
  Dochi:
    type: application
    platform: macOS
    sources:
      - path: Dochi
        excludes:
          - Info.plist
          - Resources
      - path: Dochi/Resources/Assets.xcassets
        buildPhase: resources
      - path: Dochi/Resources/SupabaseConfig.plist
        buildPhase: resources
      - path: Dochi/Resources/Models
        buildPhase: resources
        optional: true
    info:
      path: Dochi/Info.plist
      properties:
        CFBundleName: 도치
        CFBundleDisplayName: 도치
        NSMicrophoneUsageDescription: "음성 인식을 위해 마이크 접근이 필요합니다."
        NSSpeechRecognitionUsageDescription: "음성 명령을 텍스트로 변환하기 위해 음성 인식 권한이 필요합니다."
        NSRemindersFullAccessUsageDescription: "미리알림을 생성하고 관리하기 위해 접근이 필요합니다."
        NSCameraUsageDescription: "아바타가 사용자의 얼굴을 따라가기 위해 카메라 접근이 필요합니다."
    entitlements:
      path: Dochi/Dochi.entitlements
    dependencies:
      - package: onnxruntime-swift-package-manager
        product: onnxruntime
      - package: mcp-swift-sdk
        product: MCP
      - package: supabase-swift
        product: Supabase
      - package: VRMKit
        product: VRMKit
      - package: VRMKit
        product: VRMRealityKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hckim.dochi
        PRODUCT_NAME: Dochi
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: Dochi/Dochi.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: XEF9KH7N43
        SWIFT_STRICT_CONCURRENCY: targeted
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  DochiCLI:
    type: tool
    platform: macOS
    sources:
      - path: DochiCLI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hckim.dochi.cli
        PRODUCT_NAME: dochi
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_STRICT_CONCURRENCY: targeted

  DochiTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: DochiTests
    dependencies:
      - target: Dochi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hckim.dochi.tests
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES

  DochiUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: DochiUITests
    dependencies:
      - target: Dochi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hckim.dochi.uitests
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
