name: Dochi
options:
  bundleIdPrefix: com.hckim
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  onnxruntime-swift-package-manager:
    url: https://github.com/microsoft/onnxruntime-swift-package-manager.git
    from: "1.20.0"

targets:
  Dochi:
    type: application
    platform: macOS
    sources:
      - path: Dochi
        excludes:
          - Info.plist
    info:
      path: Dochi/Info.plist
      properties:
        CFBundleDisplayName: Dochi
        NSMicrophoneUsageDescription: "음성 인식을 위해 마이크 접근이 필요합니다."
        NSSpeechRecognitionUsageDescription: "음성 명령을 텍스트로 변환하기 위해 음성 인식 권한이 필요합니다."
    entitlements:
      path: Dochi/Dochi.entitlements
    dependencies:
      - package: onnxruntime-swift-package-manager
        product: onnxruntime
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hckim.dochi
        PRODUCT_NAME: Dochi
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: Dochi/Dochi.entitlements
        SWIFT_STRICT_CONCURRENCY: targeted
